[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bidon_zk = "4Pfc1jdDXX4EMFoe7FxNGMfQmSgZSegJn7DCHkxbnfXz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf"
